- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=1024']
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-json
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: debug-statements
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=no]
    - id: pretty-format-json
      args: [--autofix]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

- repo: https://github.com/willthames/ansible-lint.git
  sha: v4.1.1a0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      args: [
        "--exclude=roles",
        "--exclude=basic/roles"
      ]
